wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.4
    cli_version: 0.15.8
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693066328.201524
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 23
      4: 3.9.4
      5: 0.15.8
      8:
      - 1
      - 5
